### ISSUE TITLE
UI - BloodtestResulsts.aspx - SampleType should be dropdown

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#10] opened 2015-01-02 21:45 UTC
Blood test type should be data driven from SampleType table using the following sp:  usp_SlTargeSampleType 'person'  (this only exists in the LCCHP-Dev database at current.

**Comment by okkam1** [comment] 2015-03-17 08:03
duplicate of: 

https://github.com/okkam1/BLT/issues/98

**Closed as completed by okkam1** 2015-03-17 08:03 UTC
