### ISSUE TITLE
UI - Blood Test Results test type should be dropdown list

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#38] opened 2015-02-20 02:53 UTC
test type should be data driven from this stored procedure and parameter

DECLARE @return_value int
EXEC @return_value = [dbo].[usp_SlTargetSampleType]
@Sample_Target = N'person'

**Comment by okkam1** [comment] 2015-03-17 08:02
duplicate of this issue:

https://github.com/okkam1/BLT/issues/98

**Closed as completed by okkam1** 2015-03-17 08:02 UTC
Labels: enhancement
